# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("meta_en", models.CharField(blank=True, max_length=80)),
                ("meta_ru", models.CharField(blank=True, max_length=80)),
                ("title_en", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200)),
                ("description_en", models.TextField(blank=True)),
                ("description_ru", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("links", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "slug"]},
        ),
        migrations.CreateModel(
            name="SiteText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=120)),
                ("lang", models.CharField(choices=[("en", "English"), ("ru", "Русский")], max_length=5)),
                ("value", models.TextField(blank=True)),
            ],
            options={"ordering": ["key", "lang"], "unique_together": {("key", "lang")}},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lang", models.CharField(choices=[("en", "English"), ("ru", "Русский")], max_length=5)),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["lang", "order"]},
        ),
    ]
