# Generated by Django 5.2.13 on 2026-05-26 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_visitlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("openrouter", "OpenRouter")],
                        default="openai",
                        max_length=24,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4o-mini", "OpenAI: GPT-4o mini"),
                            ("gpt-4.1-nano", "OpenAI: GPT-4.1 nano"),
                            ("gpt-4.1-mini", "OpenAI: GPT-4.1 mini"),
                            (
                                "meta-llama/llama-3.3-70b-instruct:free",
                                "OpenRouter: Llama 3.3 70B free",
                            ),
                            (
                                "deepseek/deepseek-chat-v3-0324:free",
                                "OpenRouter: DeepSeek Chat free",
                            ),
                            (
                                "qwen/qwen3-235b-a22b:free",
                                "OpenRouter: Qwen3 235B free",
                            ),
                        ],
                        default="gpt-4o-mini",
                        max_length=120,
                    ),
                ),
                (
                    "custom_model",
                    models.CharField(
                        blank=True,
                        help_text="Optional override if the model is not in the dropdown.",
                        max_length=160,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("base_url", models.URLField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="ai_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="cover_alt_en",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="project",
            name="cover_alt_ru",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="project",
            name="cover_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="detail_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="detail_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="result_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="result_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="role_en",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="role_ru",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="year",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="ProjectDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=80)),
                (
                    "prompt",
                    models.TextField(help_text="Raw project notes for AI generation."),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Extra tone, audience, constraints, or links.",
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("title_ru", models.CharField(blank=True, max_length=200)),
                ("meta_en", models.CharField(blank=True, max_length=80)),
                ("meta_ru", models.CharField(blank=True, max_length=80)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_ru", models.TextField(blank=True)),
                ("detail_en", models.TextField(blank=True)),
                ("detail_ru", models.TextField(blank=True)),
                ("problem_en", models.TextField(blank=True)),
                ("problem_ru", models.TextField(blank=True)),
                ("solution_en", models.TextField(blank=True)),
                ("solution_ru", models.TextField(blank=True)),
                ("result_en", models.TextField(blank=True)),
                ("result_ru", models.TextField(blank=True)),
                ("role_en", models.CharField(blank=True, max_length=160)),
                ("role_ru", models.CharField(blank=True, max_length=160)),
                ("year", models.CharField(blank=True, max_length=20)),
                ("cover_image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                ("ai_model", models.CharField(blank=True, max_length=80)),
                ("ai_response", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ai_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_drafts",
                        to="core.aiproviderconfig",
                    ),
                ),
                (
                    "published_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_from_drafts",
                        to="core.project",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=160)),
                ("title_ru", models.CharField(blank=True, max_length=160)),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("caption_en", models.CharField(blank=True, max_length=240)),
                ("caption_ru", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TelegramPostDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("sent", "Sent"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("channel_hint", models.CharField(blank=True, max_length=120)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telegram_drafts",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
