# Generated by Django 5.2.17 on 2026-10-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role_en',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='role_ru',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='projectdraft',
            name='role_en',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='projectdraft',
            name='role_ru',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
